apiVersion: v1
kind: Pod
metadata:
  name: pynn-pod-
  namespace: pynn-clients
  labels:      # 标签
    app: pynn
spec:
  restartPolicy: Always
  containers:
    - name: pynn-
      image: registry.cn-hangzhou.aliyuncs.com/lvyi/pynn:1.1.4
      imagePullPolicy: IfNotPresent
      workingDir: /home/containerData/
      volumeMounts:
        - name: pynn
          mountPath: /home/containerData/
      resources:
        requests:
          cpu: 1
          memory: 256Mi
      ports: 
        - containerPort: 8888
          hostPort: 8899
  volumes:
    - name: pynn
      hostPath:
        path: /home/work/ClientDir/
        type: DirectoryOrCreate